import type { EditorThemeClasses } from 'lexical'

export const EditorTheme: EditorThemeClasses = {
  paragraph: 'mb-1',
  heading: {
    h1: 'text-3xl font-bold',
    h2: 'text-2xl font-bold',
    h3: 'text-xl font-bold',
    h4: 'text-lg font-bold',
    h5: 'text-base font-bold',
    h6: 'text-sm font-bold',
  },
  list: {
    ul: 'list-disc pl-6',
    ol: 'list-decimal pl-6',
    listitem: 'mb-0.5',
    listitemChecked: 'line-through text-muted-foreground',
    listitemUnchecked: '',
    nested: {
      listitem: 'list-none',
    },
  },
  quote: 'border-l-4 border-muted-foreground pl-4 italic text-muted-foreground',
  code: 'block font-mono bg-muted rounded p-2 text-sm my-1',
  codeHighlight: {
    atrule: 'text-blue-500',
    attr: 'text-blue-500',
    boolean: 'text-orange-500',
    builtin: 'text-green-500',
    cdata: 'text-muted-foreground',
    char: 'text-green-500',
    class: 'text-yellow-500',
    'class-name': 'text-yellow-500',
    comment: 'text-muted-foreground italic',
    constant: 'text-orange-500',
    deleted: 'text-red-500',
    doctype: 'text-muted-foreground',
    entity: 'text-orange-500',
    function: 'text-yellow-500',
    important: 'text-purple-500',
    inserted: 'text-green-500',
    keyword: 'text-blue-500',
    namespace: 'text-purple-500',
    number: 'text-orange-500',
    operator: 'text-foreground',
    prolog: 'text-muted-foreground',
    property: 'text-orange-500',
    punctuation: 'text-foreground',
    regex: 'text-purple-500',
    selector: 'text-green-500',
    string: 'text-green-500',
    symbol: 'text-orange-500',
    tag: 'text-red-500',
    url: 'text-blue-500',
    variable: 'text-purple-500',
  },
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'font-mono bg-muted rounded px-1 text-sm',
  },
  link: 'text-primary underline',
}
